# See for more - https://github.com/shadowsocks/shadowsocks-rust/blob/817a98b81a9b3620c0302340368522739b45286c/README.md#tunnel-local-client
---
version: "3.8"

networks:
  net:
    ipam:
      config:
        - subnet: 10.8.1.0/24

services:
  shadowsocks:
    image: ghcr.io/oldtyt/shadowsocks_v2ray_docker
    restart: always
    ports:
      - "80:80"
    environment:
      - PASSWORD=PASSWORD
      - DOMAIN=SS.DOMAIN.TLD
    networks:
      net:
        ipv4_address: 10.8.1.4

  wg-easy:
    environment:
      - WG_HOST=WG.DOMAIN.TLD
      - PASSWORD=PASSWORD
      - WG_DEFAULT_DNS=10.8.1.3
    image: weejewel/wg-easy
    container_name: wg-easy
    volumes:
      - /mnt/docker/wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      # - "51821:51821/tcp"
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      net:
        ipv4_address: 10.8.1.2

  pihole:
    image: pihole/pihole
    container_name: pihole
    environment:
      - WEBPASSWORD=PASSWORD
    volumes:
      - '/mnt/docker/pihole/etc/pihole:/etc/pihole'
      - '/mnt/docker/pihole/etc/dnsmasq.d:/etc/dnsmasq.d'
    restart: always
    networks:
      net:
        ipv4_address: 10.8.1.3
